import { BadgeCheck, CalendarDays, FileText, Landmark, Scale, Search, ShieldCheck } from "lucide-react";
import Image from "next/image";
import Link from "next/link";

export default function HomePage() {
  return <>
    <section className="hero"><div className="container hero-grid"><div><span className="eyebrow">Presencia institucional con propósito</span><h1>Defender la dignidad. <em>Documentar la verdad.</em></h1><p>Interventores comprometidos con la observación, la documentación y la promoción de los derechos humanos, con actuación responsable y verificable.</p><div className="button-row"><Link className="button primary" href="/identificaciones"><Search/>Verificar una identificación</Link><Link className="button outline" href="/contacto">Solicitar contacto</Link></div></div><div className="hero-seal"><Image src="/assets/logo-senidh.webp" width={520} height={520} alt="Escudo SENIDH" priority/></div></div></section>
    <section className="trust"><div className="container trust-grid"><div><Scale/><span><strong>Actuación responsable</strong>Principios, legalidad y documentación</span></div><div><BadgeCheck/><span><strong>Identidad verificable</strong>Credenciales enlazadas al Directorio</span></div><div><ShieldCheck/><span><strong>Vocación de servicio</strong>Derechos, justicia y dignidad</span></div></div></section>
    <section className="section"><div className="container"><header className="section-heading"><div><span className="kicker">Nuestra labor</span><h2>Intervención con principios</h2></div><p>Acciones orientadas a observar, documentar, acompañar y fortalecer una cultura efectiva de respeto a la dignidad humana.</p></header><div className="cards"><article><b>01</b><h3>Observación</h3><p>Presencia institucional para registrar hechos relevantes mediante metodologías responsables y trazables.</p></article><article><b>02</b><h3>Documentación</h3><p>Integración ordenada de información y evidencias, con respeto a la privacidad y al debido proceso.</p></article><article><b>03</b><h3>Vinculación</h3><p>Colaboración con instituciones y actores sociales para impulsar respuestas y soluciones duraderas.</p></article></div></div></section>
    <section className="section soft"><div className="container"><header className="section-heading"><div><span className="kicker">Información pública</span><h2>Actividad institucional</h2></div><p>Consulta actividades, instrumentos de colaboración y comunicaciones oficiales de SENIDH.</p></header><div className="feature-cards"><Link href="/eventos"><CalendarDays/><h3>Eventos</h3><p>Jornadas, encuentros y actividades públicas.</p><span>Consultar →</span></Link><Link href="/convenios"><Landmark/><h3>Convenios</h3><p>Instrumentos de colaboración institucional.</p><span>Consultar →</span></Link><Link href="/oficios"><FileText/><h3>Oficios</h3><p>Comunicaciones y documentos públicos.</p><span>Consultar →</span></Link></div></div></section>
    <section className="section verify-callout"><div className="container verify-panel"><div><span className="eyebrow">Consulta oficial</span><h2>¿La persona está acreditada?</h2><p>Comprueba el folio, fotografía, puesto, territorio, vigencia y estado actual.</p></div><form action="/identificaciones" method="get"><label htmlFor="credential-home">Número de identificación</label><input id="credential-home" name="credencial" placeholder="Ej. SENIDH-CHIH-0001" required/><button className="button navy" type="submit">Verificar identificación</button><small>El QR impreso en cada credencial abre su perfil individual dentro del Directorio.</small></form></div></section>
  </>;
}
